export const TOMSK_CENTER = {
  lat: 56.48464,
  lng: 84.94817,
  label: "Томск",
};

export const practicePlaces = [
  {
    id: "english-campus",
    title: "English Campus Club",
    category: "Разговорная практика",
    track: "English",
    lat: 56.4698,
    lng: 84.9486,
    address: "район университетской рощи",
    description: "Живая практика диалогов: small talk, вопросы в поездке и короткие ролевые сценарии.",
    format: "Офлайн встреча",
    schedule: "среда, 19:00",
    reward: 30,
  },
  {
    id: "python-lab",
    title: "Python Lab Tomsk",
    category: "Практикум",
    track: "Python",
    lat: 56.4819,
    lng: 84.9507,
    address: "центр города",
    description: "Интенсив по мини-скриптам: CSV, автоматизация рутины и разбор ошибок в небольших группах.",
    format: "Курсы офлайн",
    schedule: "суббота, 12:00",
    reward: 45,
  },
  {
    id: "figma-studio",
    title: "Figma Studio Session",
    category: "Дизайн-практика",
    track: "Figma",
    lat: 56.4976,
    lng: 84.9731,
    address: "площадка у набережной",
    description: "Практика сеток, компонентов и быстрой презентации экрана портфолио.",
    format: "Воркшоп",
    schedule: "вторник, 18:30",
    reward: 40,
  },
  {
    id: "data-cafe",
    title: "Data Cafe",
    category: "Самостоятельная практика",
    track: "Python",
    lat: 56.4753,
    lng: 84.9614,
    address: "рядом с учебными корпусами",
    description: "Удобное место, чтобы закрыть практику по чтению файлов и собрать первый личный трекер.",
    format: "Самостоятельный чек-ин",
    schedule: "каждый день",
    reward: 20,
  },
  {
    id: "travel-dialogs",
    title: "Travel Dialogs Spot",
    category: "Ролевая практика",
    track: "English",
    lat: 56.4889,
    lng: 84.9298,
    address: "западнее центра",
    description: "Сценарии аэропорта, отеля и кафе: можно прогнать фразы перед поездкой.",
    format: "Парная практика",
    schedule: "пятница, 17:30",
    reward: 35,
  },
];

export const practiceEvents = [
  {
    id: "event-python-csv",
    title: "CSV без боли: мини-проект за вечер",
    topic: "Python",
    date: "24 мая",
    time: "12:00",
    place: "Python Lab Tomsk",
    level: "начальный",
    description: "Разбор чтения CSV, подсчёта сумм и вывода простого отчёта.",
    reward: 45,
  },
  {
    id: "event-english-trip",
    title: "Английский для поездки: аэропорт и отель",
    topic: "English",
    date: "26 мая",
    time: "19:00",
    place: "English Campus Club",
    level: "beginner",
    description: "Ролевые карточки, короткие диалоги и тренировка уточняющих вопросов.",
    reward: 30,
  },
  {
    id: "event-figma-components",
    title: "Figma: компоненты и варианты",
    topic: "Figma",
    date: "28 мая",
    time: "18:30",
    place: "Figma Studio Session",
    level: "intermediate",
    description: "Собираем карточку курса, состояния и простой набор UI-компонентов.",
    reward: 40,
  },
  {
    id: "event-portfolio-review",
    title: "Ревью учебного результата",
    topic: "Маршрут",
    date: "31 мая",
    time: "16:00",
    place: "онлайн + офлайн",
    level: "любой",
    description: "Покажи мини-проект или экран и получи следующий практический шаг.",
    reward: 25,
  },
];
